name: static.yml

on:
  push:
    paths:
      - publications/**
      - README.md
      - .github/**
      - _config.yml
      - _sass/color_schemes/wider.scss
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Updates the Publication List
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run yaml2md
        run: |
          python yaml2md.py .
      - name: Copy the README to index for Jekyll
        run: |
          cat README.md >> index.md
          cat index.md
          ls
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  # Deploy static content to Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Get PDF&HTML
  convert:
    runs-on: ubuntu-latest
    needs: deploy
    name: Get PDF&HTML
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Markdown to PDF and HTML
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: README.md
          output_dir: renders
          build_html: true
          build_pdf: true
          table_of_contents: true
      - uses: actions/upload-artifact@v4
        with:
          name: renders
          path: renders