name: Updates the Publication List

on:
  push:
    paths:
      - publications/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  yaml2md:
    name: yaml2md
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Run yaml2md
        run: |
          python yaml2md.py .

      - name: Commit changes with Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: '(automatic) yaml2md Action'
          add: 'README.md'